// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Note: This config is optional. Prisma generate works with just the schema file.
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

// Only load config if DATABASE_URL is available (for migrations)
// For client generation, Prisma uses the schema file directly
const databaseUrl = process.env.DATABASE_URL;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use placeholder if DATABASE_URL not available (e.g., during build)
    // This won't be used for client generation, only for migrations
    url: databaseUrl || "postgresql://placeholder:placeholder@localhost:5432/placeholder",
  },
});

