# Generated by Django 4.2.3 on 2023-09-08 19:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('services', '0001_initial'), ('services', '0002_alter_servicetag_description'), ('services', '0003_service_link'), ('services', '0004_alter_service_link'), ('services', '0005_alter_service_link'), ('services', '0006_alter_service_link'), ('services', '0007_certificate_service_certificates'), ('services', '0008_service_prime_tag'), ('services', '0009_service_logo'), ('services', '0010_servicescreenshot'), ('services', '0011_rename_logo_servicescreenshot_image'), ('services', '0012_country_servicecategory_service_categories_and_more'), ('services', '0013_auto_20230903_1534'), ('services', '0014_servicemention'), ('services', '0015_servicerating_serviceratingreview'), ('services', '0016_certificateorganisation_and_more'), ('services', '0017_remove_certificate_organisation'), ('services', '0018_alter_certificate_specification')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(choices=[('iso', 'ISO')])),
                ('specification', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('tags', models.ManyToManyField(to='services.servicetag')),
                ('link', models.URLField()),
                ('certificates', models.ManyToManyField(to='services.certificate')),
                ('prime_tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prime_tag', to='services.servicetag')),
                ('logo', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_text', models.CharField(blank=True, default='', max_length=300)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='screenshots/')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='categories',
            field=models.ManyToManyField(to='services.servicecategory'),
        ),
        migrations.AddField(
            model_name='service',
            name='countries',
            field=models.ManyToManyField(to='services.country'),
        ),
        migrations.CreateModel(
            name='ServiceMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('link', models.URLField(max_length=400)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(choices=[('trustpilot', 'TRUSTPILOT')], max_length=50)),
                ('score', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRatingReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('score', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('service_rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='services.servicerating')),
            ],
        ),
        migrations.CreateModel(
            name='CertificateOrganisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='certificate',
            name='organisation_entity',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.certificateorganisation'),
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='organisation',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='specification',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
