# Generated by Django 4.2.3 on 2023-09-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_squashed_0018_alter_certificate_specification'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='bio',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
