# Generated by Django 4.2.3 on 2023-09-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_service_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='certificateorganisation',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='certificateorganisation',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
