# Generated by Django 4.2.3 on 2023-09-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_certificate_image_certificateorganisation_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='categories/'),
        ),
    ]
