# Generated by Django 4.2.3 on 2023-10-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0024_servicefeature_service_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicefeature',
            name='icon',
            field=models.CharField(max_length=200),
        ),
    ]
