# Generated by Django 4.2.3 on 2023-10-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0025_alter_servicefeature_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='categories',
            field=models.ManyToManyField(related_name='category_services', to='services.servicecategory'),
        ),
        migrations.AlterField(
            model_name='service',
            name='tags',
            field=models.ManyToManyField(related_name='tag_services', to='services.servicetag'),
        ),
    ]
