# Generated by Django 4.2.10 on 2024-02-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0026_alter_service_categories_alter_service_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceratingreview',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
