# Generated by Django 4.2.10 on 2024-02-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0027_serviceratingreview_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemention',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
