// Currency mapping for different countries
export const COUNTRY_CURRENCY_MAP: { [key: string]: string } = {
    'Germany': 'EUR',
    'United Kingdom': 'GBP',
    'United States': 'USD',
    'Canada': 'CAD',
    'Australia': 'AUD',
    'France': 'EUR',
    'Italy': 'EUR',
    'Spain': 'EUR',
    'Netherlands': 'EUR',
    'Belgium': 'EUR',
    'Austria': 'EUR',
    'Switzerland': 'CHF',
    'Sweden': 'SEK',
    'Norway': 'NOK',
    'Denmark': 'DKK',
    'Finland': 'EUR',
    'Poland': 'PLN',
    'Czech Republic': 'CZK',
    'Hungary': 'HUF',
    'Slovakia': 'EUR',
    'Slovenia': 'EUR',
    'Croatia': 'EUR',
    'Bulgaria': 'BGN',
    'Romania': 'RON',
    'Greece': 'EUR',
    'Portugal': 'EUR',
    'Ireland': 'EUR',
    'Luxembourg': 'EUR',
    'Malta': 'EUR',
    'Cyprus': 'EUR',
    'Estonia': 'EUR',
    'Latvia': 'EUR',
    'Lithuania': 'EUR',
    'Japan': 'JPY',
    'South Korea': 'KRW',
    'China': 'CNY',
    'India': 'INR',
    'Brazil': 'BRL',
    'Mexico': 'MXN',
    'Argentina': 'ARS',
    'Chile': 'CLP',
    'Colombia': 'COP',
    'Peru': 'PEN',
    'Uruguay': 'UYU',
    'Paraguay': 'PYG',
    'Bolivia': 'BOB',
    'Ecuador': 'USD',
    'Venezuela': 'VES',
    'Guyana': 'GYD',
    'Suriname': 'SRD',
    'French Guiana': 'EUR',
    'South Africa': 'ZAR',
    'Nigeria': 'NGN',
    'Kenya': 'KES',
    'Ghana': 'GHS',
    'Ethiopia': 'ETB',
    'Tanzania': 'TZS',
    'Uganda': 'UGX',
    'Morocco': 'MAD',
    'Algeria': 'DZD',
    'Tunisia': 'TND',
    'Egypt': 'EGP',
    'Libya': 'LYD',
    'Sudan': 'SDG',
    'Chad': 'XAF',
    'Niger': 'XOF',
    'Mali': 'XOF',
    'Burkina Faso': 'XOF',
    'Senegal': 'XOF',
    'Guinea': 'GNF',
    'Sierra Leone': 'SLL',
    'Liberia': 'LRD',
    'Ivory Coast': 'XOF',
    'Togo': 'XOF',
    'Benin': 'XOF',
    'Cameroon': 'XAF',
    'Central African Republic': 'XAF',
    'Equatorial Guinea': 'XAF',
    'Gabon': 'XAF',
    'Republic of the Congo': 'XAF',
    'Democratic Republic of the Congo': 'CDF',
    'Angola': 'AOA',
    'Zambia': 'ZMW',
    'Zimbabwe': 'ZWL',
    'Botswana': 'BWP',
    'Namibia': 'NAD',
    'Lesotho': 'LSL',
    'Eswatini': 'SZL',
    'Mozambique': 'MZN',
    'Madagascar': 'MGA',
    'Mauritius': 'MUR',
    'Seychelles': 'SCR',
    'Comoros': 'KMF',
    'Mayotte': 'EUR',
    'Reunion': 'EUR',
    'Djibouti': 'DJF',
    'Somalia': 'SOS',
    'Eritrea': 'ERN',
    'Burundi': 'BIF',
    'Rwanda': 'RWF',
    'Malawi': 'MWK'
};

// Get currency for a country
export const getCurrencyForCountry = (country: string): string => {
    return COUNTRY_CURRENCY_MAP[country] || 'USD';
};

// Format price with currency
export const formatPrice = (price: number, currency: string): string => {
    const formatter = new Intl.NumberFormat('en-US', {
        style: 'currency',
        currency: currency,
        minimumFractionDigits: 0,
        maximumFractionDigits: 2,
    });
    
    return formatter.format(price);
};

// Get currency symbol
export const getCurrencySymbol = (currency: string): string => {
    const symbols: { [key: string]: string } = {
        'EUR': '€',
        'USD': '$',
        'GBP': '£',
        'JPY': '¥',
        'CAD': 'C$',
        'AUD': 'A$',
        'CHF': 'CHF',
        'SEK': 'kr',
        'NOK': 'kr',
        'DKK': 'kr',
        'PLN': 'zł',
        'CZK': 'Kč',
        'HUF': 'Ft',
        'BGN': 'лв',
        'RON': 'lei',
        'CNY': '¥',
        'KRW': '₩',
        'INR': '₹',
        'BRL': 'R$',
        'MXN': '$',
        'ARS': '$',
        'CLP': '$',
        'COP': '$',
        'PEN': 'S/',
        'UYU': '$',
        'PYG': '₲',
        'BOB': 'Bs',
        'VES': 'Bs',
        'GYD': '$',
        'SRD': '$',
        'ZAR': 'R',
        'NGN': '₦',
        'KES': 'KSh',
        'GHS': '₵',
        'ETB': 'Br',
        'TZS': 'TSh',
        'UGX': 'USh',
        'MAD': 'د.م.',
        'DZD': 'د.ج',
        'TND': 'د.ت',
        'EGP': 'ج.م',
        'LYD': 'ل.د',
        'SDG': 'ج.س.',
        'XAF': 'FCFA',
        'XOF': 'CFA',
        'GNF': 'FG',
        'SLL': 'Le',
        'LRD': 'L$',
        'CDF': 'FC',
        'AOA': 'Kz',
        'ZMW': 'ZK',
        'ZWL': '$',
        'BWP': 'P',
        'NAD': 'N$',
        'LSL': 'L',
        'SZL': 'L',
        'MZN': 'MT',
        'MGA': 'Ar',
        'MUR': '₨',
        'SCR': '₨',
        'KMF': 'CF',
        'DJF': 'Fdj',
        'SOS': 'S',
        'ERN': 'Nfk',
        'BIF': 'FBu',
        'RWF': 'FRw',
        'MWK': 'MK'
    };
    
    return symbols[currency] || currency;
}; 