# Generated by Django 4.2.3 on 2023-07-31 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetag',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
