# Generated by Django 4.2.3 on 2023-07-31 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_servicetag_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
