# Generated by Django 4.2.3 on 2023-08-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_service_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='link',
            field=models.URLField(),
        ),
    ]
