# Generated by Django 4.2.3 on 2023-08-23 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_certificate_service_certificates'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='prime_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prime_tag', to='services.servicetag'),
        ),
    ]
