# Generated by Django 4.2.3 on 2023-08-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_service_prime_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
    ]
