# Generated by Django 4.2.3 on 2023-08-28 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_service_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_text', models.CharField(blank=True, default='', max_length=300)),
                ('logo', models.ImageField(blank=True, default=None, null=True, upload_to='screenshots/')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='services.service')),
            ],
        ),
    ]
