# Generated by Django 4.2.3 on 2023-08-28 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_servicescreenshot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicescreenshot',
            old_name='logo',
            new_name='image',
        ),
    ]
