# Generated by Django 4.2.3 on 2023-09-03 15:34

from django.db import migrations


# def migrate_to_product_model(apps, schema_editor):
#     Service = apps.get_model('services', 'Service')
#     Country = apps.get_model('services', 'Country')
#     ServiceCategory = apps.get_model('services', 'ServiceCategory')
#     ServiceTag = apps.get_model('services', 'ServiceTag')
#
#     for service in Service.objects.all():
#         for tag in service.tags.all():
#             if tag.name.lower() == "uk":
#                 c, _ = Country.get_or_create(name="United Kingdom")
#                 service.countries.add(c)
#


class Migration(migrations.Migration):
    dependencies = [
        ('services', '0012_country_servicecategory_service_categories_and_more'),
    ]

    operations = [
    ]
