# Generated by Django 4.2.3 on 2023-09-05 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_auto_20230903_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('link', models.URLField(max_length=400)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='services.service')),
            ],
        ),
    ]
