# Generated by Django 4.2.3 on 2023-09-08 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_servicerating_serviceratingreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateOrganisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='certificate',
            name='organisation',
            field=models.CharField(choices=[('iso', 'ISO')]),
        ),
        migrations.AddField(
            model_name='certificate',
            name='organisation_entity',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.certificateorganisation'),
        ),
    ]
