# Generated by Django 4.2.3 on 2023-09-08 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_certificateorganisation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='organisation',
        ),
    ]
