# Generated by Django 4.2.3 on 2023-09-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_remove_certificate_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='specification',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
