#!/bin/bash
echo "To find your Cloud SQL instance connection name:"
echo ""
echo "1. Go to: https://console.cloud.google.com/sql/instances?project=free-trial-first-project"
echo "2. Click on your PostgreSQL instance"
echo "3. Copy the 'Connection name' (shown at the top)"
echo ""
echo "The format will be:"
echo "  free-trial-first-project:REGION:INSTANCE_NAME"
echo ""
echo "Common regions: us-central1, us-east1, europe-west1, asia-east1"
echo ""
echo "Once you have it, run:"
echo "  ./start-cloud-sql-proxy.sh free-trial-first-project:REGION:INSTANCE_NAME"
