# Generated by Django 4.2.3 on 2023-07-31 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_created_at_blogpost_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
