# Generated by Django 4.2.3 on 2023-07-31 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_link'),
        ('blog', '0003_blogpost_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='service',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='services.service'),
        ),
    ]
