# Generated by Django 4.2.3 on 2023-07-31 22:38

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpost_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
